export const GET_VEHICLE_SUCCESS = "GET_VEHICLE_SUCCESS"
export const GET_VEHICLE_FAILED = "GET_VEHICLE_FAILED"

export const UPDATE_VEHICLE = "UPDATE_VEHICLE"
export const UPDATE_VEHICLE_SUCCESS = "UPDATE_VEHICLE_SUCCESS"
export const UPDATE_VEHICLE_FAILED = "UPDATE_VEHICLE_FAILED"

export const DELETE_VEHICLE_SUCCESS = "DELETE_VEHICLE_SUCCESS"
export const DELETE_VEHICLE_FAILED = "DELETE_VEHICLE_FAILED"